[profile.default]
src = "src"
out = "out"
libs = ["lib","dependencies"]

auto_detect_remappings = false

[dependencies]
forge-std = "1.11.0"
"@openzeppelin-contracts" = "5.5.0-rc.1"
"projA" = { version = "1", git = "https://github.com/heueristik/projA.git", branch = "feature/reproduce-bug" }

[soldeer]
recursive_deps = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
